FPS = 60

HEIGHT_WINDOW = 612
WIDTH_WINDOW = 1024

HEIGHT_WINDOW_INTERFACE = 250
WIDTH_WINDOW_INTERFACE = 612

POSITION_CAMERA_X = -50
POSITION_CAMERA_Y = 5
POSITION_CAMERA_Z = -55

POSITION_AXIS_X = 0
POSITION_AXIS_Y = 0
POSITION_AXIS_Z = 0

BG_COLOR_R = 65
BG_COLOR_G = 105
BG_COLOR_B = 225

BG_COLOR_INTERFACE_R = 30
BG_COLOR_INTERFACE_G = 30
BG_COLOR_INTERFACE_B = 30

VERTICES_COLOR_R = 255
VERTICES_COLOR_G = 255
VERTICES_COLOR_B = 255

PRIMITIVE_COLOR_R = 0
PRIMITIVE_COLOR_G = 0
PRIMITIVE_COLOR_B = 0

FACES_COLOR_R = 245
FACES_COLOR_G = 167
FACES_COLOR_B = 0

SPEED_TRANSLATE_X = 0.0002
SPEED_TRANSLATE_Y = 0.0002
SPEED_TRANSLATE_Z = 0.0002

SPEED_TRANSLATE_OBJECT = 0.005

SPEED_MOVING_CAMERA = 0.3
SPEED_ROTATION_CAMERA = 0.015

MAUS_CONTROL = False
MAUS_NOT = False

AREA_OF_TRANQUILITY_CAMERA = 200

FONT_INSCRIPTIONS = 32
SLEEVE_AXES_LENGTH = 50

THICKNESS_POLYGONS = 2
THICKNESS_VERTICES = 2

MOVING_OBJECT = True

DRAWING_VERTICALS = False
DRAWING_AXES = False
DRAWING_AXES_OBJECT = False

BUILDING_AXIS = True

RESOURCES_OBJECTS = [('../resources/home.obj', (0, 0, 0)),
                     ('../resources/home.obj', (25, 0, 0))]
